apiVersion: v1
kind: Service
metadata:
  name: taskflow-frontend-svc
spec:
  type: NodePort
  selector:
    app: taskflow-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080