apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskflow-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: taskflow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskflow-frontend-svc
                port:
                  number: 80